

services:
  
  frontend:
   platform: linux/amd64
   build:
    context: .
    dockerfile: ./frontend/Dockerfile
   ports:
    - "5173:80"  # Ajuste selon ton projet (3000 si besoin)
   volumes:
    - ./frontend:/app  # Recharge le code sans rebuild
   depends_on:
    - backend
   networks:
    - app_network
   restart: unless-stopped
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Monte le fichier de config Nginx
      - ./nginx/ssl:/etc/nginx/ssl:ro                # Monte les certificats SSL
      - ./frontend/dist:/app/dist                 # Monte les fichiers du frontend
    ports:
      - "80:80"                                   # Expose le port HTTP
      - "443:443"                                 # Expose le port HTTPS
    depends_on:
      - backend                                   # Assure-toi que le backend démarre avant Nginx
      - frontend                                  # Assure-toi que le frontend démarre avant Nginx
    networks:
      - app_network


  backend:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/var/www
    ports:
      - "8080:8080"

    depends_on:
      - db
    networks:
      - app_network
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ofour
      DB_USERNAME: root
      DB_PASSWORD: eliezeribghi
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    platform: linux/amd64
    image: mysql:5.7
    container_name: my-mysql
    restart: always
    tty: true
    environment:
     MYSQL_ROOT_PASSWORD: eliezeribghi
     MYSQL_DATABASE: ofour
    ports:
    - "3306:3306"
    volumes:
    - mysql_data:/var/lib/mysql
    - ./bdd/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
    - app_network
    command: --lower_case_table_names=2
    healthcheck:
     test: ["CMD", "mysqladmin", "ping", "-h", "192.168.1.247", "-uroot", "-peliezeribghi"]
     interval: 10s
     timeout: 5s
     retries: 5

  # sonarqube:
  #   image: sonarqube:lts-community
  #   depends_on:
  #     - sonar_db
  #   environment:
  #     SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
  #     SONAR_JDBC_USERNAME: sonar
  #     SONAR_JDBC_PASSWORD: sonar
  #   ports:
  #     - "9001:9000"
  #   volumes:
  #     - sonarqube_conf:/opt/sonarqube/conf
  #     - sonarqube_data:/opt/sonarqube/data
  #     - sonarqube_extensions:/opt/sonarqube/extensions
  #     - sonarqube_logs:/opt/sonarqube/logs
  #     - sonarqube_temp:/opt/sonarqube/temp



networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
