
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80" # Le frontend est accessible via http://localhost   
    depends_on:
      - backend  # Le frontend dépend du backend
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www 
    ports:
     - "${PORT}:${PORT}"  # Le backend est accessible via http://localhost:8080
 
    depends_on:
      - db  # Le backend dépend de la base de données
    networks:
      - app_network
    environment:
      PORT: 8080
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ofour
      DB_USERNAME: root
      DB_PASSWORD: root
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  composer:
    image: composer:latest
    container_name: composer-installer
    working_dir: /var/www/backend 
    volumes:
     - ./backend:/var/www/backend
    command: ["composer", "install"]
  db:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Mot de passe pour l'utilisateur root
      MYSQL_DATABASE: ofour      # Nom de la base de données à créer
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    command: --lower_case_table_names=2
    healthcheck:
     test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root", "--password=root"]
     interval: 30s
     timeout: 5s
     retries: 3



networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:

