version: '3.8'  # ou '3' si vous ne voulez pas spécifier la version

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
    ports:
      - "3307:3306"  # Utilisez 3306 ou 3307 selon votre configuration
    networks:
      - app-network

  adminer:
    image: adminer
    ports:
      - "8081:8080"  # Utilisez 8081 ou un autre port si nécessaire
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
