name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: eliezeribghi
          MYSQL_DATABASE: ofour
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, bcmath, curl, zip

      - name: Copy .env file
        run: printf "%s" "${{ secrets.MY_ENV_FILE }}" > ./backend/.env
      - name: Move to Laravel directory
        run: cd backend && php artisan config:clear


      - name: Test Laravel DB connection
        run: php artisan migrate:status

      - name: Install Composer dependencies
        working-directory: ./backend
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Set Laravel .env DB_HOST
        run: echo "DB_HOST=127.0.0.1" >> .env

      - name: Generate APP_KEY
        working-directory: ./backend
        run: php artisan key:generate

      - name: Test MySQL connection
        run: |
         mysql -h 127.0.0.1 -u root -p'eliezeribghi' -e "SHOW DATABASES;"
      - name: Wait for MySQL
        run: |
         while ! mysqladmin ping -h"192.168.1.247" -P"3306" -u"root" -p"eliezeribghi" --silent; do
         echo "Waiting for MySQL..."
         sleep 5
         done
         echo "MySQL is ready!"
      


      - name: Configure Laravel environment
        working-directory: ./backend
        run: |
          echo "DB_CONNECTION=mysql" >> $GITHUB_ENV
          echo "DB_HOST=mysql" >> $GITHUB_ENV
          echo "DB_PORT=3306" >> $GITHUB_ENV
          echo "DB_DATABASE=ofour" >> $GITHUB_ENV
          echo "DB_USERNAME=root" >> $GITHUB_ENV
          echo "DB_PASSWORD=eliezeribghi" >> $GITHUB_ENV

      - name: Clear Laravel cache
        working-directory: ./backend
        run: php artisan config:clear

      - name: Run database migrations
        working-directory: ./backend
        run: php artisan migrate --force

      - name: Run tests
        working-directory: ./backend
        run: php artisan test
  
  sonarqube:
    runs-on: ubuntu-latest
    needs: build  # Assure-toi que ce job attend la fin du job build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      

      - name: Install SonarScanner
        run: |
          curl -Lo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner.zip
          echo "$PWD/sonar-scanner-5.0.1.3006-linux/bin" >> $GITHUB_PATH

      - name: Start SonarQube
        run: |
          docker run -d --name sonar \
          -p 9003:9000 \  # Port du conteneur SonarQube
          -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true \
          sonarqube:lts

      - name: Wait for SonarQube
        run: |
          while ! curl -s http://localhost:9003/api/system/status | grep -q "OK"; do
            echo "Waiting for SonarQube..."
            sleep 5
          done
          echo "SonarQube is ready!"

      - name: Run SonarScanner (Backend)
        run: |
          cd backend
          sonar-scanner \
            -Dsonar.host.url="http://localhost:9003" \
            -Dsonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Run SonarScanner (Frontend)
        run: |
          cd frontend
          sonar-scanner \
            -Dsonar.host.url="http://localhost:9003" \
            -Dsonar.login="${{ secrets.SONAR_TOKEN }}"
