name: CI

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: eliezeribghi
          MYSQL_DATABASE: ofour
          MYSQL_USER: appuser
          MYSQL_PASSWORD: apppassword
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
   
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.0'
          extensions: mbstring, xml, bcmath, curl, zip

      - name: Copy .env file
        run: echo "$MY_ENV_FILE" > ./backend/.env
        env:
          MY_ENV_FILE: ${{ secrets.MY_ENV_FILE }}

      - name: Install Composer dependencies
        working-directory: ./backend
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Generate APP_KEY
        working-directory: ./backend
        run: php artisan key:generate

      - name: Attente de MySQL
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"3307" -u"root" -p"eliezeribghi" --silent; do
            echo "Attente de MySQL..."
            sleep 5
          done
          echo "MySQL est prêt !"

      - name: Vérification de la connexion MySQL
        run: |
          mysql -h127.0.0.1 -P3307 -uroot -peliezeribghi -e "SHOW DATABASES;"

      - name: Configuration de l'application
        working-directory: ./backend
        run: |
           echo "DB_CONNECTION=mysql" >> $GITHUB_ENV
           echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
           echo "DB_PORT=3306" >> $GITHUB_ENV
           echo "DB_DATABASE=ofour" >> $GITHUB_ENV
           echo "DB_USERNAME=root" >> $GITHUB_ENV
           echo "DB_PASSWORD=eliezeribghi" >> $GITHUB_ENV

      - name: Vérification de la connexion MySQL
        run: |
          mysql -h127.0.0.1 -P3307 -uappuser -papppassword -e "SHOW DATABASES;"

      - name: Run database migrations
        run: php artisan migrate --force
        env:
          DB_CONNECTION: ${{ env.DB_CONNECTION }}
          DB_HOST: ${{ env.DB_HOST }}
          DB_PORT: ${{ env.DB_PORT }}
          DB_DATABASE: ${{ env.DB_DATABASE }}
          DB_USERNAME: ${{ env.DB_USERNAME }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}

      - name: Run tests
        working-directory: ./backend
        run: php artisan test
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3307
          DB_DATABASE: ofour
          DB_USERNAME: appuser
          DB_PASSWORD: apppassword
      