name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Étape 1: Vérifier le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v2

      # Étape 2: Configurer PHP et installer les dépendances
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.0'
          extensions: mbstring, xml, bcmath, curl, zip

      # Étape 3: Copier le fichier .env depuis le secret
      - name: Copy .env file
        run: echo "$MY_ENV_FILE" > ./backend/.env
        env:
          MY_ENV_FILE: ${{ secrets.MY_ENV_FILE }}

      # Étape 4: Installer les dépendances Composer
      - name: Install Composer dependencies
        working-directory: ./backend
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      # Étape 5: Générer la clé d'application (si nécessaire)
      - name: Generate APP_KEY
        working-directory: ./backend
        run: php artisan key:generate

      # Étape 6: Lancer les tests
      - name: Run tests
        working-directory: ./backend
        run: php artisan test --no-interaction
