name: CI

on: [push, pull_request]

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      # Étape 1: Vérifier le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v2

      # Étape 2: Configurer Node.js pour le frontend
      - name: Setup Node.js (Frontend)
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Étape 3: Installer les dépendances du frontend
      - name: Install frontend dependencies
        working-directory: ./frontend # Dossier du frontend
        run: npm install

      # Étape 4: Construire le frontend
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # Étape 5: Configurer Node.js pour le backend (si nécessaire, répéter pour backend)
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
         php-version: '8.2.0'
         extensions: mbstring, xml, bcmath, curl, zip

      # Étape 6: Copier le fichier .env dans le dossier backend
      - name: Copy .env file
        run: echo "$MY_ENV_FILE" > ./backend/.env

      # Étape 7: Installer les dépendances du backend
      - name: Install Composer dependencies
        working-directory: ./backend # Dossier du backend
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      # Étape 8: Générer la clé d'application
      - name: Generate APP_KEY
        working-directory: ./backend
        run: php artisan key:generate

      # Étape 9: Tester ou construire le backend
      - name: Build or Test backend
        working-directory: ./backend
        run: php artisan test # Ou `npm test` si tu as des tests pour le backend
